= docs.rubocop.org

This repository contains RuboCop's documentation site. It's home to both
the documentation of RuboCop itself, plus that of its core extensions (the ones
maintained by RuboCop's Core Team).

The site is generated from the AsciiDoc files in the
link:https://github.com/rubocop/rubocop/tree/master/docs[docs] folder of
RuboCop's GitHub repo (and the core RuboCop extensions like `rubocop-rspec`) and
is published to https://docs.rubocop.org.  link:https://antora.org[Antora] is
used to convert the manual into HTML.  The filesystem layout is described
https://docs.antora.org/antora/3.1/standard-directories/[here].

You can find a list of all the documentation modules that are weaved together in the
final site in `antora-playbook.yml`.

To make changes to the manual you simply have to change the files under `docs` in the relevant
repository.
The docs will be regenerated manually periodically.

== Installing Antora

NOTE: You'll have to install `node.js` before installing Antora.

Installing Antora is super simple:

[source]
----
$ make install
----

Check out https://docs.antora.org/antora/3.1/install/install-antora/[the detailed installation instructions]
if you run into any problems.

== Building the Site

You can build the documentation locally from this repo.

[source]
----
$ cd docs.rubocop.org
$ make build
----

TIP: You can preview your changes by opening `build/site/index.html` in your favorite browser.

If you want to make changes to the manual's page structure you'll have to edit
link:https://github.com/rubocop/rubocop/blob/master/doc/modules/ROOT/nav.adoc[nav.adoc].

== Deploying to GitHub Pages

NOTE: You'll need commit access to the repository for this to work.

The site is automatically deployed to GitHub pages using a GitHub Action.
The action will be triggered by any push to the `master` branch.
It can also be triggered manually if needed.

== Using Docker

If you prefer not to install Antora on your local machine, you can build the documentation
inside a Docker container like this:

[source]
----
$ cd docs.rubocop.org
$ docker run -u $(id -u) -v $PWD:/antora:Z --rm -t antora/antora --cache-dir=./.cache/antora antora-playbook.yml
----

Note that despite the message saying `Open file:///antora/build/site/index.html in a browser to view your site.`, you
you should actually look for `build/site/index.html` in the current directory. (that's because we've mounted the
current directory as `/antora` in the container)

TIP: You can read more about running Antora in a container in the https://docs.antora.org/antora/latest/antora-container/[official docs].

== Updating the Playbook

When cutting new releases you'll have to updated `antora-playbook.yml` to mention
their relevant tags from which the documentation needs to be build. Here's how this
looks for one of the projects:

[source]
----
- url: https://github.com/rubocop/rubocop-performance.git
  branches: master
  tags: ['v1.7.1', 'v1.8.1']
  start_path: docs
----

TIP: You need to add one such block for each new RuboCop module you're adding to the docs site.

After releases of the main RuboCop gem you also need to update the default landing
version (it should always be the latest version).

== Troubleshooting

The most common mistake that people make is to forget to update the version of an Antora docs module
after cutting a release. This will result in an error saying you've got the same version in two branches (e.g. `master`
and `v1.0`). Fixing this is pretty simple - just update the version to `master` in `antora.yml`.
